# Generated by Django 2.2 on 2021-02-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
